<?xml version="1.0"?>
<?mso-application progid="Excel.Sheet"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
 xmlns:o="urn:schemas-microsoft-com:office:office"
 xmlns:x="urn:schemas-microsoft-com:office:excel"
 xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
 xmlns:html="http://www.w3.org/TR/REC-html40">
 <DocumentProperties xmlns="urn:schemas-microsoft-com:office:office">
  <Author>Autor</Author>
  <LastAuthor>Autor</LastAuthor>
  <Created>2006-12-04T20:10:16Z</Created>
  <Company>Empresa</Company>
  <Version>11.5606</Version>
 </DocumentProperties>
 <ExcelWorkbook xmlns="urn:schemas-microsoft-com:office:excel">
  <WindowHeight>6105</WindowHeight>
  <WindowWidth>10425</WindowWidth>
  <WindowTopX>600</WindowTopX>
  <WindowTopY>90</WindowTopY>
  <ProtectStructure>False</ProtectStructure>
  <ProtectWindows>False</ProtectWindows>
 </ExcelWorkbook>
 <Styles>
 
 <Style ss:ID="moneda" ss:Name="moneda">
 	<Alignment ss:Horizontal="Center" ss:Vertical="Center" ss:WrapText="1" />
	 <Borders>
  		<Border   ss:Position="Bottom" ss:Weight="2" ss:LineStyle="Continuous" />
		<Border   ss:Position="Left" ss:Weight="2" ss:LineStyle="Continuous" />
		<Border   ss:Position="Right" ss:Weight="2" ss:LineStyle="Continuous" />
		<Border   ss:Position="Top" ss:Weight="2" ss:LineStyle="Continuous" />
  	 </Borders>
	 <Font ss:Size="8" ss:Bold='1' /> 
	<NumberFormat ss:Format="Currency" />
	
</Style>
 
  <Style ss:ID="Default" ss:Name="Normal">
   <Alignment ss:Vertical="Bottom"/>
   <Borders/>
   <Font/>
   <Interior/>
   <NumberFormat/>
   <Protection/>
  </Style>
  
 <Style ss:ID="headd" ss:Name="head">
 	 <Alignment ss:Horizontal="Center" ss:Vertical="Center" ss:WrapText="1" />
 	 <Borders>
  		<Border   ss:Position="Bottom" ss:Weight="2" ss:LineStyle="Continuous" />
		<Border   ss:Position="Left" ss:Weight="2" ss:LineStyle="Continuous" />
		<Border   ss:Position="Right" ss:Weight="2" ss:LineStyle="Continuous" />
		<Border   ss:Position="Top" ss:Weight="2" ss:LineStyle="Continuous" />
  	 </Borders>
     <Font ss:Size="8" ss:Bold='1' /> 
  </Style>
 </Styles>
 
 